### ISSUE TITLE
PROBLEM：ros2 communicate with dds

### ISSUE THREAD

**Issue by friendsocket** [eProsima/SOSS-DDS#20]
Hi friend. I just have a question regarding communication between Fastrps and ROS2 in my Ubuntu 18.04 system.

My selfdefined YAML file:
``` 
systems:
    dds:
      type: dds
      dynamic types:
        struct std_msgs__String:
          string: "data"
    ros2:
       type: ros2

routes:
    ros2_to_dds: {from: ros2, to: dds}
    dds_to_ros2: {from: dds, to: ros2}

topics:
    hello_ros2: {type: "std_msgs/String", route: dds_to_ros2}
    hello_dds: {type: "std_msgs/String", route: ros2_to_dds}
```

My selfdefined IDL file:
```
struct std_msgs__String
{
	string data;
};
```

After that, i modify the file HelloSubscriber.cxx that generated by my selfdefined Hello.idl. 
I changed the topic name to be consistent with my own Yaml file. then compiled the revelant files.
`Rparam.topic.topicName = "hello_dds";`

My purpose is to let DDS recieve the message from Ros2.  then i open three terminals.
**First terminal:**
`soss ~/rosis_workspace/soss/src/soss-dds/dds/sample/dds_to_ros2_dbt.yaml`
**Second terminal:**
`ros2 topic pub -r 1 /hello_dds std_msgs/String "{data: \"Hello, dds\"}"`
**Third terminal:**
`./Hello subscriber`

The phenomenon is the second terminal send message constantly, but the third terminal has nothing output. 
When i try to let DDS send message to Ros2 that using the same way. It can work normally.

Do you have any advice, thanks.

**Comment by golizheh** [comment]
Hi @friendsocket 

When I run your YAML file: soss ~/rosis_workspace/soss/src/soss-dds/dds/sample/dds_to_ros2_dbt.yaml

I will get the following error:
The config-file [dds_ros2.yaml] is missing a dictionary for [systems]! You must specify at least two systems in your config-file.

have you get this error?

Could you also explain where do you edit Hello subscriber file?

**Comment by golizheh** [comment]
My Setup with the same YAML file have the following error:
soss-ros2 could not find .mix file for message type: std_msgs/String
 -- Make sure that you have generated the soss-ros2 extension for that message type by calling soss_rosidl_mix(PACKAGES <package> MIDDLEWARES ros2) in your build system!
Failed to load middlewares!

is any help?

**Comment by lemunozm** [comment]
Hi,
@golizheh, I think your problem is related with the issue https://github.com/eProsima/SOSS-DDS/issues/21.
@friendsocket, You say that third therminal has no output, but the first one has? Soss will be printed the conversion for each topic sent. Can you see that?

**Comment by sparkskraps** [comment]
@lemunozm 
When dds send message to ros2, the soss print message as below:
```
[soss-dds]: participant not provided in configuration file. UDP default participant will be created
[soss-dds]: configured!
[soss-dds]: publisher created. topic: hello_dds, type: std_msgs/String
[soss-dds]: subscriber created. topic: hello_ros2, type: std_msgs/String
[soss-dds][subscriber]: matched (hello_ros2) 
[soss-dds][subscriber]: translate message: dds -> soss (hello_ros2) 
[soss-dds][subscriber]: translate message: dds -> soss (hello_ros2) 
[soss-dds][subscriber]: translate message: dds -> soss (hello_ros2) 
[soss-dds][subscriber]: translate message: dds -> soss (hello_ros2) 

```
When ros2 say hello to dds, the soss terminal print nothing:
```
[soss-dds]: participant not provided in configuration file. UDP default participant will be created.
[soss-dds]: configured!
[soss-dds]: publisher created. topic: hello_dds, type: std_msgs/String
[soss-dds]: subscriber created. topic: hello_ros2, type: std_msgs/String
[soss-dds][publisher]: matched (hello_dds) 
```
Although the terminal that execute  command <ros2 topic pub -r 1 /hello_dds std_msgs/String "{data: \"Hello, dds\"}">  constantly output.
```
publisher: beginning loop
publishing eProsima/FastDDS-SH#1: std_msgs.msg.String(data='Hello, dds')

publishing eProsima/FastDDS-SH#2: std_msgs.msg.String(data='Hello, dds')

publishing eProsima/FastDDS-SH#3: std_msgs.msg.String(data='Hello, dds')

publishing eProsima/FastDDS-SH#4: std_msgs.msg.String(data='Hello, dds')

publishing eProsima/FastDDS-SH#5: std_msgs.msg.String(data='Hello, dds')

publishing eProsima/FastDDS-SH#6: std_msgs.msg.String(data='Hello, dds')

publishing eProsima/FastDDS-SH#7: std_msgs.msg.String(data='Hello, dds')
```
So maybe the message that the ros2 send is not arrive to the soss plugin, so it also cannot arrive to dds.  but what reasons maybe cause this?

**Comment by lemunozm** [comment]
Hi @friendsocket,

Maybe the problem is related with the *fastrtps* version your are using. At this moment, *soss-dds* plugin is working with *fastrtps* 1.7. Could you confirm your version?

When you compile *soss-dds*, it will use the found *fastrtps*, if no *fasrtps* is found, It will compile the *fastrtps* from the thirdparty (the correct version).

We are working in support newer versions of *fastrtps* right now.

**Comment by sparkskraps** [comment]
@lemunozm 
Maybe not, I switch the branch to 1.7.X.
```
ubuntu@cscsh:~/ros2_ws/src/eProsima/Fast-RTPS$ git branch -a
* (HEAD detached at 6a6f79c42)
  info
  master
  remotes/origin/1.7.x
  remotes/origin/1.8.x
  remotes/origin/HEAD -> origin/master
  remotes/origin/bugfix/5712
  remotes/origin/bugfix/check-remote-permissions
  remotes/origin/bugfix/protect-history-size

then i execute : git checkout remotes/origin/1.7.x

ubuntu@cscsh:~/ros2_ws/src/eProsima/src/Fast-RTPS$ git branch
* (HEAD detached at origin/1.7.x)
  info
  master
```
Is the above procedure correct? 
then i recompile the fastRTPS code and also soss-dds : colcon build --packages-up-to soss-dds.
Try again, it's still not work, the phenomenon just like before.  Confused...

**Comment by lemunozm** [comment]
*soss-dds* uses exactly the tag v1.7.2 although your branch should works too.
Is your Hello example compiled also in 1.7?

We will try to reproduce your scenario here.

**Comment by sparkskraps** [comment]
```
ubuntu@cscsh:~/ros2_ws/src/eProsima/src/Fast-RTPS/examples/C++/HelloWorldExample/dbt$ ls
build           Hello.cxx  Hello.idl           HelloPublisher.h     HelloPubSubTypes.cxx  HelloSubscriber.cxx
CMakeLists.txt  Hello.h    HelloPublisher.cxx  HelloPubSubMain.cxx  HelloPubSubTypes.h    HelloSubscriber.h
ubuntu@cscsh:~/ros2_ws/src/eProsima/src/Fast-RTPS/examples/C++/HelloWorldExample/dbt$ cd build
ubuntu@cscsh:~/ros2_ws/src/eProsima/src/Fast-RTPS/examples/C++/HelloWorldExample/dbt/build$ ll
total 272
drwxr-xr-x 3 dbt dbt   4096 Oct 22 17:50 ./
drwxr-xr-x 3 dbt dbt   4096 Oct 22 17:56 ../
-rw-r--r-- 1 dbt dbt  13387 Oct 22 17:50 CMakeCache.txt
drwxr-xr-x 6 dbt dbt   4096 Oct 22 17:50 CMakeFiles/
-rw-r--r-- 1 dbt dbt   1610 Oct 22 17:50 cmake_install.cmake
-rwxr-xr-x 1 dbt dbt 214216 Oct 22 17:50 Hello*
-rw-r--r-- 1 dbt dbt  13148 Oct 22 17:50 libHello_lib.a
-rw-r--r-- 1 dbt dbt   8817 Oct 22 17:50 Makefile

ubuntu@cscsh:~/ros2_ws/src/eProsima/src/Fast-RTPS/examples/C++/HelloWorldExample/dbt/build$ date
Tue Oct 22 18:42:36 CST 2019
```
Yeap, I also recompiled the Hello example.

**Comment by sparkskraps** [comment]
@lemunozm 
By the way, My soss-dds branch is:
```
ubuntu@cscsh:~/rosis_workspace/soss/src/soss-dds/dds$ git branch
* dashing
  master
ubuntu@cscsh:~/rosis_workspace/soss/src/soss-dds/dds$ git branch -a
* dashing
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/feature/announcement_period_fix
  remotes/origin/feature/dashing
  remotes/origin/feature/windows
  remotes/origin/feature/windows_dashing
  remotes/origin/master
```
The reason that i switch the branch from master to dashing is when colcon build soss-dds, it will occur errors like this:
```
.......
/home/dbt/rosis_workspace/soss/src/soss-dds/dds/src/Conversion.cpp: In member function ‘eprosima::fastrtps::types::ResponseCode DynamicDataSOSS::GetDescriptorSOSS(eprosima::fastrtps::types::MemberDescriptor&, eprosima::fastrtps::types::MemberId) const’:
/home/dbt/rosis_workspace/soss/src/soss-dds/dds/src/Conversion.cpp:36:19: error: ‘mDescriptors’ was not declared in this scope
         auto it = mDescriptors.find(id);
                   ^~~~~~~~~~~~
/home/dbt/rosis_workspace/soss/src/soss-dds/dds/src/Conversion.cpp:36:19: note: suggested alternative: ‘descriptors_’
         auto it = mDescriptors.find(id);
                   ^~~~~~~~~~~~
                   descriptors_
/home/dbt/rosis_workspace/soss/src/soss-dds/dds/src/Conversion.cpp:39:26: error: ‘class eprosima::fastrtps::types::MemberDescriptor’ has no member named ‘CopyFrom’; did you mean ‘copy_from’?
             return value.CopyFrom(it->second);
                          ^~~~~~~~
                          copy_from
.......
```
I hope this has nothing to do with the issue problem.

**Comment by golizheh** [comment]
Dear @lemunozm  

I also have same problem as @friendsocket (message is received by soss but NOT by subscriber)

My Fastrtps is newst version, Should I also switch to v7?
Or it will be work with version 9 as well.
If I have to switch to v7 could you explain the correct way of switching?

Thanks in advance

**Comment by golizheh** [comment]
@friendsocket 
Just a small question for testing sending message from DDS to ROS2, I have setupmy three terminal as follwo:(I have also change topic name to  Wparam.topic.topicName = "hello_ros2";)
./HelloWorld publisher
Starting 
Publisher created, waiting for Subscribers.

Second terminal :  
soss dds_ros2.yaml [soss-dds]: participant not provided in configuration file. UDP default participant will be created.
[soss-dds]: configured!
[soss-dds]: publisher created. topic: hello_dds, type: std_msgs/String
[soss-dds]: subscriber created. topic: hello_ros2, type: std_msgs/String

Third Terminal:
ros2 topic  echo /hello_ros2

But I can not get message from DDS to ROS2? do you have same setup? Am I forget something to apply?

**Comment by lemunozm** [comment]
Hi @friendsocket , @golizheh ,

I think I know what can be your problem. You said that you modified `HelloSubscriber.cxx` to change your type. I see then that your path is `~/ros2_ws/src/eProsima/src/Fast-RTPS/examples/C++/HelloWorldExample`, which means that you are using the builtin HelloWorld example. All files of `HelloWorldExample` were generated by `Fast-RTPS-Gen`. So, there are other files there (as the serialization/deserialization files) that also must be changed. Instead of modifying all these files by your self, you should use the `Fast-RTPS-Gen` tool.

Other solution is to use `DynamicTypes`. This allows creating the type in runtime without code generation.
See https://fast-rtps.docs.eprosima.com/en/latest/dynamictypes.html .

**Comment by lemunozm** [comment]
We have tested `ros2-dds` communication in both directions with your IDL type and works fine.

I attached here a `fastrtps` branch that modifies the `DynamicHelloWorld` with your IDL. The branch comes from v1.7.2, so you can see the necessary changes over the current `DynamicHelloWorldExample` with a simple `git diff`. I hope this is useful.

`fastrtps` branch: [example/helloworld-ros2-compatible](https://github.com/eProsima/Fast-RTPS/tree/example/helloworld-ros2-compatible/examples/C%2B%2B/DynamicHelloWorldExample)

**Comment by golizheh** [comment]
Hi @lemunozm

I have used fastgen to generat files . 
But as I can see I have problem in both direction: 

1. ROS2 Pub and FastRTSP SUB
```idl
struct Hello
{
    string data;
};
```
I have generate all files  by using fastgen.
My YAML Fils is :
```yaml
systems:
    dds:
      type: dds
      dynamic types:
        struct std_msgs__String:
          string: "data"
    ros2:
       type: ros2

routes:
    ros2_to_dds: {from: ros2, to: dds}
    dds_to_ros2: {from: dds, to: ros2}

topics:
    Hello_ros2: {type: "std_msgs/String", route: dds_to_ros2}
    HelloPubSubTopic: {type: "std_msgs/String", route: ros2_to_dds}
```
In the first terminal I run:
```
soss dds_ros2.yaml
[soss-dds]: participant not provided in configuration file. UDP default participant will be created.
[soss-dds]: configured!
[soss-dds]: publisher created. topic: HelloPubSubTopic, type: std_msgs/String
[soss-dds]: subscriber created. topic: Hello_ros2, type: std_msgs/String
[soss-dds][publisher]: translate message: soss -> dds (HelloPubSubTopic) 
[soss-dds][publisher]: translate message: soss -> dds (HelloPubSubTopic) 
[soss-dds][publisher]: translate message: soss -> dds (HelloPubSubTopic) 
[soss-dds][publisher]: translate message: soss -> dds (HelloPubSubTopic) 
```
Second Terminal:  
```
ros2 topic pub -r 1 /HelloPubSubTopic std_msgs/String "{data: \"Hello, dds\"}"
publisher: beginning loop
publishing eProsima/FastDDS-SH#1: std_msgs.msg.String(data='Hello, dds')

publishing eProsima/FastDDS-SH#2: std_msgs.msg.String(data='Hello, dds')

publishing eProsima/FastDDS-SH#3: std_msgs.msg.String(data='Hello, dds')
```
Third terminal:
```
~/Fast-RTPS-Gen/scripts/build$ ./Hello subscriber
Starting 
Waiting for Data, press Enter to stop the Subscriber.
```
As You can see it does not get any thing, in the other direction I also can not get any adata.

Thanks and look forward to hearing from you

**Comment by lemunozm** [comment]
@golizheh , 

the problem seems to be that your IDL type is called `Hello`, but when you specify the topic `HelloPubSubTopic` in the soss yaml, it is defined as `std_msgs/String`. Because the types differs, no DDS matching is performed.

My recommendation is to regenerate the IDL with `Fast-RTPS-gen` defining the IDL as follows:
```ìdl
struct std_msgs__String
{
    string data;
};
```

PD: I edited your comment to add the markdown code style.

**Comment by golizheh** [comment]
@lemunozm 
Following previous conversation,
I also have tried to change the name of idl file so I have this scenario:
std_msgs__String.idl (All files are generated automatically from this idl file)
In the Yaml file:
topics:
    golizheh: {type: "std_msgs/String", route: dds_to_ros2}
    My_Topic: {type: "std_msgs/String", route: ros2_to_dds}
I also have update publisher and subscriber file just for topic name

Then First Terminal: ./std_msgs__String publisher

second soss dds_ros2.yaml

but in the third terminal when I run ros2 topic list 
I can not see my topic called golizhe.

I think the problem as you mentioned is something in the topic name but I do not understand how can I change it?
As you said "but when you specify the topic HelloPubSubTopic in the soss yaml, it is defined as std_msgs/String. Because the types differs, no DDS matching is performed" 
So How can I define my names?

**Comment by lemunozm** [comment]
Hi @golizheh,

It looks like you are using a `fastrtps` version higher than `1.7.2`. The branch I modified is a simple commit over the v1.7.2 tag. You can see the difference between the `v1.7.2` and `example/helloworld-ros2-compatible` [here](https://github.com/eProsima/Fast-RTPS/compare/v1.7.2...example/helloworld-ros2-compatible).

You have 2 options:
- You can use the same commit as `example/helloworld-ros2-compatible` in order to test the functionality.
- You can update your own example or create a new one from last `fastrtps` version with the same logic changes found in the previous diff.

**Comment by lemunozm** [comment]
For clarifying:

`soss-dds` is currently using `fastrtps v1.7.2`. It must be compiled with this version. But `fastrtps v1.7.2` can communicate with other `fastrtps` versions, as the new `1.9.x`.

**Comment by golizheh** [comment]
could you please tell me the safe way to downgarde my fastrtps version to oldest (as you mentioned v1.7.2)? (I am using v9) 
Because as you said it is works with the old version, I think it can be good solution.
What do you think?

**Comment by lemunozm** [comment]
Currently, you can navigate to your own fastrtps: `/home/golizheh/Fast-RTPS/`
And there: `git checkout v1.7.2 ` or `git checkout example/helloworld-ros2-compatible` for the example already modified over `v1.7.2`.

If you download fastrtps from an empty state, you can:
```
git clone -b v1.7.2 https://github.com/eProsima/Fast-RTPS.git
```
or
```
git clone -b example/helloworld-ros2-compatible https://github.com/eProsima/Fast-RTPS.git
```
for the example.

**Comment by golizheh** [comment]
@lemunozm  Thanks for your answer, I have download V1.7.2 from an empty state (as you mentioned), but when I compiler it it is seem like it is still compiler it with v1.9 because I will get same erorr errors.
I compiler it by creating build folder and cmake .. and make.
But same erorr which is related to V1.9. 
I think it is still compiler with v1.9?

**Comment by golizheh** [comment]
First I have run:
git clone -b v1.7.2 https://github.com/eProsima/Fast-RTPS.git
Then in Fast-RTPS branch:

:~/fastrtpsV7/Fast-RTPS$ git branch -v
* (no branch) bfa38dfa5 Release 1.7.2 (#444)

**Comment by golizheh** [comment]
When I create new folder and run 
clone -b example/helloworld-ros2-compatible https://github.com/eProsima/Fast-RTPS.git
 the run :~/fastrtpsV7/Fast-RTPS$ git branch -v
* example/helloworld-ros2-compatible 024097c55 Modified DynamicHelloWorldExample for soss-dds issue eProsima/FastDDS-SH#20

But still can not compiler Dynamic HelloWorld example
As I also try to compile another example in this folder, I will also get error, but in v1.9 folder I have already compiler and run them,

**Comment by golizheh** [comment]
@lemunozm 
I figure out , it i need to compiler all packages again. It solve and Compiler 
thanks for your time

**Comment by lemunozm** [comment]
You're welcome @golizheh , 
If it is working I close the issue.

**Comment by gek40** [comment]
Hello!
I'm trying make communication via Fast-RTPS and ROS2 with help SOSS-DDS.
My trouble look like [this](https://github.com/eProsima/SOSS-DDS/issues/20#issue-508326419) issue. 
I have the Fast-RTPS with branch origin/release/1.7.2
I made the idl message:
```
struct std_msgs__String
{
   string data;
};
```
and generated a code with help fastrtpsgen. My code based on DynamicHelloWorldExample (https://github.com/gek40/dds_experiments/tree/master/DynamicStdMsgsString)
When I send a message from the Fast-RTPS publisher all is ok. Subscriber print this:
```
Starting 
Subscriber running. Please press enter to stop the Subscriber
Participant Dynm_StdMsgsString_pub discovered

onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic
Subscriber matched
onNewDataMessage from StdMsgsString_Topic with type std_msgs__String
!!! Message: String from Fast-RTPS RECEIVED
Subscriber unmatched

onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic
Participant Dynm_StdMsgsString_pub removed

```
But when I send a message from ROS2 topic through SOSS subscriber print:
```
Starting 
Subscriber running. Please press enter to stop the Subscriber
Participant RTPSParticipant discovered
Participant soss_ros2 discovered

onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic
Subscriber matched
Participant _ros2cli_publisher_std_msgs_String discovered
Participant _ros2cli_publisher_std_msgs_String removed

onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic
Participant soss_ros2 removed
Participant RTPSParticipant removed
```
SOSS print this:
```
[soss-dds]: participant not provided in configuration file. UDP default participant will be created.
[soss-dds]: configured!
[soss-dds]: publisher created. topic: StdMsgsString_Topic, type: std_msgs/String
[soss-dds][publisher]: matched (StdMsgsString_Topic) 
```
This seems like a problem in the communication of ROS2 and SOSS, because SOSS does not respond to the publication in the ROS topic.

Some ideas on this?
Thanks!
